# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-minimal',
                'doc_host': 'https://jimmiemunyi.github.io',
                'git_url': 'https://github.com/jimmiemunyi/nbdev-minimal',
                'lib_path': 'nbdev_minimal'},
  'syms': {'nbdev_minimal.core': {'nbdev_minimal.core.foo': ('core.html#foo', 'nbdev_minimal/core.py')}}}
